EquipmentManagement.Web/Controllers/EquipmentController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using EquipmentManagement.Application.Equipments.Commands;
using EquipmentManagement.Application.Equipments.Queries;
using EquipmentManagement.Domain.Entities;
using EquipmentManagement.Infrastructura.Commands.Contracts;
using EquipmentManagement.Infrastructura.Queries.Contracts;
using EquipmentManagement.Web.ViewModels.Equipments;

namespace EquipmentManagement.Web.Controllers
{
    [Authorize]
    public class EquipmentController : Controller
    {
        private readonly ICommandDispatcher commandDispatcher;
        private readonly IQueryDispatcher queryDispatcher;

        public EquipmentController(ICommandDispatcher commandDispatcher, IQueryDispatcher queryDispatcher)
        {
            this.commandDispatcher = commandDispatcher;
            this.queryDispatcher = queryDispatcher;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult MyEquipments()
        {
            return View();
        }

        [HttpGet]
        public IActionResult UserEquipments()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(EquipmentViewModel vm)
        {
            commandDispatcher.Execute(new AddEquipmentCommand(vm.Name, vm.Price, vm.Type));
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            Equipment equipment = queryDispatcher.Execute(new GetEquipmentByIdQuery(id));
            return View(ToViewModel(equipment));
        }

        [HttpPost]
        public IActionResult Edit(EquipmentViewModel vm)
        {
            commandDispatcher.Execute(new UpdateEquipmentCommand(vm.Id, vm.Name, vm.Price, vm.Type));
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Delete(int id)
        {
            commandDispatcher.Execute(new DeleteEquipmentCommand(id));
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public IActionResult Return(int requestId)
        {
            commandDispatcher.Execute(new ReturnEquipmentCommand(requestId));
            return RedirectToAction(nameof(RequestController.Details), "Request", new { id = requestId });
        }

        #region Helpers

        private EquipmentViewModel ToViewModel(Equipment equipment)
        {
            return new EquipmentViewModel
            {
                Id = equipment.Id,
                Name = equipment.Name,
                Price = equipment.Price,
                Type = equipment.Type
            };
        }

        #endregion
    }
}

EquipmentManagement.Web/Controllers/ProfileController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using EquipmentManagement.Application.Profile.Commands;
using EquipmentManagement.Infrastructura.Commands.Contracts;
using EquipmentManagement.Security;
using EquipmentManagement.Web.ViewModels.Profile;

namespace EquipmentManagement.Web.Controllers
{
    [Authorize]
    public class ProfileController : Controller
    {
        private readonly IUserContext userContext;
        private readonly ICommandDispatcher commandDispatcher;

        public ProfileController(IUserContext userContext, ICommandDispatcher commandDispatcher)
        {
            this.userContext = userContext;
            this.commandDispatcher = commandDispatcher;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Personal()
        {
            PersonalViewModel vm = new PersonalViewModel
            {
                Email = userContext.Email,
                PhoneNumber = userContext.PhoneNumber,
                FirstName = userContext.FirstName,
                LastName = userContext.LastName,
                CompanyName = userContext.CompanyName,
                CompanySite = userContext.CompanySite,
                Post = userContext.Post,
                About = userContext.About
            };

            return View(vm);
        }

        [HttpPost]
        public IActionResult Personal(PersonalViewModel vm)
        {
            commandDispatcher.Execute(new UpdatePersonalCommand
            {
                Email = vm.Email,
                PhoneNumber = vm.PhoneNumber,
                FirstName = vm.FirstName,
                LastName = vm.LastName,
                CompanyName = vm.CompanyName,
                CompanySite = vm.CompanySite,
                Post = vm.Post,
                About = vm.About
            });

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Location()
        {
            LocationViewModel vm = new LocationViewModel
            {
                Country = userContext.Country,
                StreetAddress = userContext.StreetAddress,
                Locality = userContext.Locality,
                StateOrProvince = userContext.StateOrProvince,
                Postcode = userContext.Postcode
            };

            return View(vm);
        }

        [HttpPost]
        public IActionResult Location(LocationViewModel vm)
        {
            commandDispatcher.Execute(new UpdateLocationCommand
            {
                Country = vm.Country,
                StreetAddress = vm.StreetAddress,
                Locality = vm.Locality,
                StateOrProvince = vm.StateOrProvince,
                Postcode = vm.Postcode
            });

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult ChangePassword()
        {
            return View();
        }
    }
}

EquipmentManagement.Web/Controllers/RequestController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using EquipmentManagement.Application.Equipments.Queries;
using EquipmentManagement.Application.Requets.Commands;
using EquipmentManagement.Application.Requets.Queries;
using EquipmentManagement.Infrastructura.Commands.Contracts;
using EquipmentManagement.Infrastructura.Queries.Contracts;
using EquipmentManagement.Web.ViewModels.Equipments;
using EquipmentManagement.Web.ViewModels.Requests;

namespace EquipmentManagement.Web.Controllers
{
    [Authorize]
    public class RequestController : Controller
    {
        private readonly IQueryDispatcher queryDispatcher;
        private readonly ICommandDispatcher commandDispatcher;

        public RequestController(IQueryDispatcher queryDispatcher, ICommandDispatcher commandDispatcher)
        {
            this.queryDispatcher = queryDispatcher;
            this.commandDispatcher = commandDispatcher;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult My()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Assigned()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(RequestViewModel vm)
        {
            commandDispatcher.Execute(new CreateRequestCommand(vm.Message, vm.EquipmentType));
            return RedirectToAction(nameof(My));
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            var request = queryDispatcher.Execute(new GetRequestDetailsQuery(id));
            var equipment = queryDispatcher.Execute(new GetUserEquipmentByRequestQuery(id));

            var vm = new RequestDetailsViewModel
            {
                RequestDetails = request,
                UserEquipmentInfo = equipment
            };

            return View(vm);
        }

        [HttpPost]
        public IActionResult Assigne(int id)
        {
            commandDispatcher.Execute(new AssigneRequestCommand(id));
            return RedirectToAction(nameof(Details), new { id });
        }

        [HttpGet]
        public IActionResult Approve(int id)
        {
            var request = queryDispatcher.Execute(new GetRequestDetailsQuery(id));
            var equipments = queryDispatcher.Execute(new GetEquipmentsByTypeQuery(request.EquipmentType));

            var vm = new RequestApproveViewModel
            {
                RequestId = id,
                Request = request,
                Equipments = new EquipmentSelectViewModel(equipments)
            };

            return View(vm);
        }

        [HttpPost]
        public IActionResult Approve(RequestApproveViewModel vm)
        {
            commandDispatcher.Execute(new ApproveRequestCommand
            {
                RequestId = vm.RequestId,
                EquipmentId = vm.EquipmentId,
                ExpirationDate = vm.ExpirationDate,
                Message = vm.Message
            });

            return RedirectToAction(nameof(Details), new { id = vm.Id });
        }

        [HttpGet]
        public IActionResult Cancel(int id)
        {
            var request = queryDispatcher.Execute(new GetRequestDetailsQuery(id));
            return View(request);
        }

        [HttpPost]
        public IActionResult Cancel(RequestCancelViewModel vm)
        {
            commandDispatcher.Execute(new CancelRequestCommand(vm.Id, vm.Message));
            return RedirectToAction(nameof(Details), new { id = vm.Id });
        }

        [HttpGet]
        public IActionResult Decline(int id)
        {
            var request = queryDispatcher.Execute(new GetRequestDetailsQuery(id));
            return View(request);
        }

        [HttpPost]
        public IActionResult Decline(RequestDeclineViewModel vm)
        {
            commandDispatcher.Execute(new DeclineRequestCommand(vm.Id, vm.Message));
            return RedirectToAction(nameof(Details), new { id = vm.Id });
        }

        [HttpPost]
        public IActionResult Complete(int id)
        {
            commandDispatcher.Execute(new CompleteRequestCommand(id));
            return RedirectToAction(nameof(Details), new { id });
        }
    }
}

EquipmentManagement.Web/Views/Shared/Components/HeaderUserComponent/Default.cshtml
@using EquipmentManagement.Web.Configurations
@using EquipmentManagement.Security

@inject IUserContext UserContext

<div class="kt-header__topbar-item kt-header__topbar-item--user">
    <div class="kt-header__topbar-wrapper" data-toggle="dropdown">
        <div class="kt-header__topbar-user">
            <img alt="Pic" class="kt-radius-100" src="@(String.IsNullOrEmpty(UserContext.AvatarUrl) ? PlatformConfiguration.DefaultAvatarUrl : UserContext.AvatarUrl)" />
        </div>
    </div>
    <div class="dropdown-menu dropdown-menu-fit dropdown-menu-right dropdown-menu-anim dropdown-menu-top-unround dropdown-menu-xl">
        <div class="kt-user-card kt-user-card--skin-light kt-notification-item-padding-x">
            <div class="kt-user-card__avatar">
                <img src="~/assets/media/users/default.jpg" />
            </div>
            <div class="kt-user-card__name">@UserContext.FirstName @UserContext.LastName</div>
        </div>
        <div class="kt-notification">
            <a asp-controller="Profile" asp-action="Index" class="kt-notification__item">
                <div class="kt-notification__item-icon">
                    <i class="flaticon2-calendar-3 kt-font-success"></i>
                </div>
                <div class="kt-notification__item-details">
                    <div class="kt-notification__item-title kt-font-bold">My Profile</div>
                    <div class="kt-notification__item-time">Account settings and more</div>
                </div>
            </a>
            <a asp-controller="Equipment" asp-action="MyEquipments" class="kt-notification__item">
                <div class="kt-notification__item-icon">
                    <i class="flaticon2-cube kt-font-brand"></i>
                </div>
                <div class="kt-notification__item-details">
                    <div class="kt-notification__item-title kt-font-bold">My equipments</div>
                    <div class="kt-notification__item-time">My having equipments</div>
                </div>
            </a>
            <a asp-controller="Request" asp-action="My" class="kt-notification__item">
                <div class="kt-notification__item-icon">
                    <i class="flaticon2-rocket-1 kt-font-danger"></i>
                </div>
                <div class="kt-notification__item-details">
                    <div class="kt-notification__item-title kt-font-bold">My Requests</div>
                    <div class="kt-notification__item-time">My active and completed requests</div>
                </div>
            </a>
            @if (UserContext.IsAdmin)
            {
                <a asp-controller="Request" asp-action="Assigned" class="kt-notification__item">
                    <div class="kt-notification__item-icon">
                        <i class="flaticon2-cardiogram kt-font-warning"></i>
                    </div>
                    <div class="kt-notification__item-details">
                        <div class="kt-notification__item-title kt-font-bold">Assigned requests</div>
                        <div class="kt-notification__item-time">Requests assigned to me</div>
                    </div>
                </a>
            }
            <div class="kt-notification__custom kt-space-between">
                <form asp-controller="Account" asp-action="Logout" method="post">
                    <button type="submit" class="btn btn-label btn-label-brand btn-sm btn-bold">Sign Out</button>
                </form>
            </div>
        </div>
    </div>
</div>