EquipmentManagement.Web/Controllers/EquipmentController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using EquipmentManagement.Application.Equipments.Commands;
using EquipmentManagement.Application.Equipments.Queries;
using EquipmentManagement.Domain.Entities;
using EquipmentManagement.Infrastructura.Commands.Contracts;
using EquipmentManagement.Infrastructura.Queries.Contracts;
using EquipmentManagement.Web.ViewModels.Equipments;

namespace EquipmentManagement.Web.Controllers
{
    [Authorize]
    public class EquipmentController : Controller
    {
        private readonly ICommandDispatcher commandDispatcher;
        private readonly IQueryDispatcher queryDispatcher;

        public EquipmentController(ICommandDispatcher commandDispatcher, IQueryDispatcher queryDispatcher)
        {
            this.commandDispatcher = commandDispatcher;
            this.queryDispatcher = queryDispatcher;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult MyEquipments()
        {
            return View();
        }

        [HttpGet]
        public IActionResult UserEquipments()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(EquipmentViewModel vm)
        {
            commandDispatcher.Execute(new AddEquipmentCommand(vm.Name, vm.Price, vm.Type));
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            Equipment equipment = queryDispatcher.Execute(new GetEquipmentByIdQuery(id));
            return View(ToViewModel(equipment));
        }

        [HttpPost]
        public IActionResult Edit(EquipmentViewModel vm)
        {
            commandDispatcher.Execute(new UpdateEquipmentCommand(vm.Id, vm.Name, vm.Price, vm.Type));
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Delete(int id)
        {
            commandDispatcher.Execute(new DeleteEquipmentCommand(id));
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public IActionResult Return(int requestId)
        {
            commandDispatcher.Execute(new ReturnEquipmentCommand(requestId));
            return RedirectToAction(nameof(RequestController.Details), "Request", new { id = requestId });
        }

        #region Helpers

        private EquipmentViewModel ToViewModel(Equipment equipment)
        {
            return new EquipmentViewModel
            {
                Id = equipment.Id,
                Name = equipment.Name,
                Price = equipment.Price,
                Type = equipment.Type
            };
        }

        #endregion
    }
}

EquipmentManagement.Web/Controllers/ReportController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using EquipmentManagement.Application.Reports.Equipments.Queries;
using EquipmentManagement.Application.Reports.Equipments.Queries.Models;
using EquipmentManagement.Application.Reports.Requests.Queries;
using EquipmentManagement.Application.Reports.Requests.Queries.Models;
using EquipmentManagement.Infrastructura.Queries.Contracts;
using EquipmentManagement.Web.Extensions;
using EquipmentManagement.Web.ViewModels.Reports;

namespace EquipmentManagement.Web.Controllers
{
    [Authorize]
    public class ReportController : Controller
    {
        private readonly IQueryDispatcher queryDispatcher;

        public ReportController(IQueryDispatcher queryDispatcher)
        {
            this.queryDispatcher = queryDispatcher;
        }

        public IActionResult Requests()
        {
            var reports = queryDispatcher.Execute(new GetRequestReportsQuery());
            return View(ToViewModel(reports));
        }

        public IActionResult Equipments()
        {
            var reports = queryDispatcher.Execute(new GetEquipmentReportsQuery());
            return View(ToViewModel(reports));
        }

        #region Helpers

        private EquipmentsViewModel ToViewModel(EquipmentReports reports)
        {
            return new EquipmentsViewModel
            {
                Total = reports.Total,
                UserFurnitures = CreateViewModel(reports.UserEquipmentsCount.Furnitures, "Furnitures"),
                UserDevices = CreateViewModel(reports.UserEquipmentsCount.Devices, "Devices"),
                UserAccessories = CreateViewModel(reports.UserEquipmentsCount.Accessories, "Accessories"),
                UserTools = CreateViewModel(reports.UserEquipmentsCount.Tools, "Tools"),
                RatioOfCount = CreateViewModel(reports.RatioOfCount, "count"),
                RatioOfPrice = CreateViewModel(reports.RatioOfPrice, "price", "$")
            };
        }

        private RatioDetailChartViewModel CreateViewModel(RatioOfEquipments model, string title, string symbol = null)
        {
            return new RatioDetailChartViewModel
            {
                Title = $"Ratio of user equipments {title}",
                ChartId = $"ratio-user-equipments-{title}",
                Symbol = symbol,
                Total = model.Total,
                Items = model.Items.Select(ToViewModel).ToList()
            };
        }

        private RatioDetailChartItemViewModel ToViewModel(RatioOfEquipment model)
        {
            return new RatioDetailChartItemViewModel
            {
                Label = model.Type.ToString(),
                Count = model.Value,
                Value = model.PercentValue,
                Type = model.Type.GetColorState()
            };
        }

        private UserEquipmentChartViewModel CreateViewModel(UserEquipmentCount count, string title)
        {
            return new UserEquipmentChartViewModel
            {
                UserEquipmentCount = count,
                Type = count.Type.GetColorState(),
                Title = $"User {title}",
                Label = $"Issued {title.ToLower()} count",
                ChartId = $"user-equipment-{title.ToLower()}-chart"
                
            };
        }

        private RequestsViewModel ToViewModel(RequestReports reports)
        {
            return new RequestsViewModel
            {
                FurnitureRequestCount = CreateViewModel(reports.RequestCountByType.FurnituresCount),
                AccessoryRequestCount = CreateViewModel(reports.RequestCountByType.AccessoriesCount),
                DeviceRequestCount = CreateViewModel(reports.RequestCountByType.DevicesCount),
                ToolsRequestCount = CreateViewModel(reports.RequestCountByType.ToolsCount),
                RequestsLineChartByEquipmentType = CreateViewModel(reports.RequestByMonths),
                AmChartByRequestStatus = CreateViewModel(reports.RequestByStatuses)
            };
        }

        private ProgressPercentChartViewModel CreateViewModel(RequestCountByType requests)
        {
            return new ProgressPercentChartViewModel
            {
                Value = requests.Count,
                Percent = requests.Percent,
                ColorState = requests.Type.GetColorState(),
                Title = $"Requests for {requests.Type.ToString().ToLower()}",
                SubTitle = $"All requests for {requests.Type.ToString().ToLower()}"
            };
        }

        private LineChartViewModel CreateViewModel(RequestByMonthsList list)
        {
            return new LineChartViewModel
            {
                Title = "Requests statistics",
                ChartTitle = "Requests line chart by equipment types",
                ChartSubTitle = "furnitures, accessories, devices, tools",
                ChartId = "requests-line-chart-by-equipment-type",
                Columns = list.Items
                    .Select(i => new LineChartColumnViewModel
                    {
                        Title = i.Type.ToString(),
                        Values = i.Counts
                            .Select(j => j.Count.ToString())
                    }),
                XValues = new LineChartColumnViewModel
                {
                    Title = "Month",
                    Values = list.Items
                        .FirstOrDefault()
                        ?.Counts
                        .Select(i => i.Date.ToString("Y"))
                }
            };
        }

        private AmChartViewModel CreateViewModel(RequestByStatuses statuses)
        {
            return new AmChartViewModel
            {
                Title = "Requests by statuses, yearly",
                ChartId = "requests-am-chart-by-statuses",
                Data = new AmChartDataViewModel
                {
                    Sectors = statuses.Statuses
                        .ToDictionary(i => i.Year, j => j.Values.Select(k => new AmChartSectorViewModel
                        {
                            Sector = k.Status.ToString(),
                            Size = k.Percent
                        }).ToArray()),
                    First = statuses.Statuses
                        .OrderBy(i => i.Year)
                        .First()
                        .Year,
                    Last = statuses.Statuses
                        .OrderBy(i => i.Year)
                        .Last()
                        .Year
                }
            };
        }

        #endregion
    }
}

EquipmentManagement.Web/Controllers/RequestController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using EquipmentManagement.Application.Equipments.Queries;
using EquipmentManagement.Application.Requets.Commands;
using EquipmentManagement.Application.Requets.Queries;
using EquipmentManagement.Infrastructura.Commands.Contracts;
using EquipmentManagement.Infrastructura.Queries.Contracts;
using EquipmentManagement.Web.ViewModels.Equipments;
using EquipmentManagement.Web.ViewModels.Requests;

namespace EquipmentManagement.Web.Controllers
{
    [Authorize]
    public class RequestController : Controller
    {
        private readonly IQueryDispatcher queryDispatcher;
        private readonly ICommandDispatcher commandDispatcher;

        public RequestController(IQueryDispatcher queryDispatcher, ICommandDispatcher commandDispatcher)
        {
            this.queryDispatcher = queryDispatcher;
            this.commandDispatcher = commandDispatcher;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult My()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Assigned()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(RequestViewModel vm)
        {
            commandDispatcher.Execute(new CreateRequestCommand(vm.Message, vm.EquipmentType));
            return RedirectToAction(nameof(My));
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            var request = queryDispatcher.Execute(new GetRequestDetailsQuery(id));
            var equipment = queryDispatcher.Execute(new GetUserEquipmentByRequestQuery(id));

            var vm = new RequestDetailsViewModel
            {
                RequestDetails = request,
                UserEquipmentInfo = equipment
            };

            return View(vm);
        }

        [HttpPost]
        public IActionResult Assigne(int id)
        {
            commandDispatcher.Execute(new AssigneRequestCommand(id));
            return RedirectToAction(nameof(Details), new { id });
        }

        [HttpGet]
        public IActionResult Approve(int id)
        {
            var request = queryDispatcher.Execute(new GetRequestDetailsQuery(id));
            var equipments = queryDispatcher.Execute(new GetEquipmentsByTypeQuery(request.EquipmentType));

            var vm = new RequestApproveViewModel
            {
                RequestId = id,
                Request = request,
                Equipments = new EquipmentSelectViewModel(equipments)
            };

            return View(vm);
        }

        [HttpPost]
        public IActionResult Approve(RequestApproveViewModel vm)
        {
            commandDispatcher.Execute(new ApproveRequestCommand
            {
                RequestId = vm.RequestId,
                EquipmentId = vm.EquipmentId,
                ExpirationDate = vm.ExpirationDate,
                Message = vm.Message
            });

            return RedirectToAction(nameof(Details), new { id = vm.Id });
        }

        [HttpGet]
        public IActionResult Cancel(int id)
        {
            var request = queryDispatcher.Execute(new GetRequestDetailsQuery(id));
            return View(request);
        }

        [HttpPost]
        public IActionResult Cancel(RequestCancelViewModel vm)
        {
            commandDispatcher.Execute(new CancelRequestCommand(vm.Id, vm.Message));
            return RedirectToAction(nameof(Details), new { id = vm.Id });
        }

        [HttpGet]
        public IActionResult Decline(int id)
        {
            var request = queryDispatcher.Execute(new GetRequestDetailsQuery(id));
            return View(request);
        }

        [HttpPost]
        public IActionResult Decline(RequestDeclineViewModel vm)
        {
            commandDispatcher.Execute(new DeclineRequestCommand(vm.Id, vm.Message));
            return RedirectToAction(nameof(Details), new { id = vm.Id });
        }

        [HttpPost]
        public IActionResult Complete(int id)
        {
            commandDispatcher.Execute(new CompleteRequestCommand(id));
            return RedirectToAction(nameof(Details), new { id });
        }
    }
}

EquipmentManagement.Web/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using EquipmentManagement.Infrastructura.Queries.Contracts;
using EquipmentManagement.Web.ViewModels.Users;
using EquipmentManagement.Application.Users.Queries;

namespace EquipmentManagement.Web.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private readonly IQueryDispatcher queryDispatcher;

        public UserController(IQueryDispatcher queryDispatcher)
        {
            this.queryDispatcher = queryDispatcher;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var users = queryDispatcher.Execute(new GetUsersQuery());
            var vm = new UserListViewModel { Users = users.Users };
            return View(vm);
        }

        [HttpGet]
        public IActionResult Profile(string id)
        {
            return View(nameof(Index));
        }
    }
}

EquipmentManagement.Web/Views/Shared/Components/AsideComponent/Default.cshtml
@using EquipmentManagement.Security

@inject IUserContext UserContext

<div class="kt-aside  kt-aside--fixed  kt-grid__item kt-grid kt-grid--desktop kt-grid--hor-desktop" id="kt_aside">
    <div class="kt-aside__brand kt-grid__item " id="kt_aside_brand">
        <div class="kt-aside__brand-logo">
            <a href="/">
                <img alt="Logo" src="/assets/media/logos/logo-12.png">
            </a>
        </div>
        <div class="kt-aside__brand-tools">
            <button class="kt-aside__brand-aside-toggler" id="kt_aside_toggler"><span></span></button>
        </div>
    </div>
    <div class="kt-aside-menu-wrapper kt-grid__item kt-grid__item--fluid" id="kt_aside_menu_wrapper">
        <div id="kt_aside_menu" class="kt-aside-menu " data-ktmenu-vertical="1" data-ktmenu-scroll="1">
            <ul class="kt-menu__nav ">

                <li class="kt-menu__item " aria-haspopup="true">
                    <a href="/" class="kt-menu__link ">
                        <i class="kt-menu__link-icon flaticon2-architecture-and-city"></i>
                        <span class="kt-menu__link-text">Dashboard</span>
                    </a>
                </li>

                <li class="kt-menu__section ">
                    <h4 class="kt-menu__section-text">Management</h4>
                </li>

                <li class="kt-menu__item ">
                    <a asp-controller="User" asp-action="Index" class="kt-menu__link ">
                        <i class="kt-menu__link-icon flaticon-users"></i><span class="kt-menu__link-text">Users</span>
                    </a>
                </li>

                <li class="kt-menu__item  kt-menu__item--submenu" aria-haspopup="true" data-ktmenu-submenu-toggle="hover">
                    <a href="javascript:;" class="kt-menu__link kt-menu__toggle">
                        <i class="kt-menu__link-icon flaticon2-rocket-1"></i>
                        <span class="kt-menu__link-text">Requests</span>
                        <i class="kt-menu__ver-arrow la la-angle-right"></i>
                    </a>
                    <div class="kt-menu__submenu ">
                        <span class="kt-menu__arrow"></span>
                        <ul class="kt-menu__subnav">
                            <li class="kt-menu__item " aria-haspopup="true">
                                <a asp-controller="Request" asp-action="Create" class="kt-menu__link ">
                                    <i class="kt-menu__link-bullet kt-menu__link-bullet--dot"><span></span></i>
                                    <span class="kt-menu__link-text">Create request</span>
                                </a>
                            </li>
                            <li class="kt-menu__item " aria-haspopup="true">
                                <a asp-controller="Request" asp-action="My" class="kt-menu__link ">
                                    <i class="kt-menu__link-bullet kt-menu__link-bullet--dot"><span></span></i>
                                    <span class="kt-menu__link-text">My requests</span>
                                </a>
                            </li>
                            @if (UserContext.IsAdmin)
                            {
                                <li class="kt-menu__item " aria-haspopup="true">
                                    <a asp-controller="Request" asp-action="Index" class="kt-menu__link ">
                                        <i class="kt-menu__link-bullet kt-menu__link-bullet--dot"><span></span></i>
                                        <span class="kt-menu__link-text">All requests</span>
                                    </a>
                                </li>
                                <li class="kt-menu__item " aria-haspopup="true">
                                    <a asp-controller="Request" asp-action="Assigned" class="kt-menu__link ">
                                        <i class="kt-menu__link-bullet kt-menu__link-bullet--dot"><span></span></i>
                                        <span class="kt-menu__link-text">Assigned requests</span>
                                    </a>
                                </li>
                            }
                        </ul>
                    </div>
                </li>

                <li class="kt-menu__item  kt-menu__item--submenu" aria-haspopup="true" data-ktmenu-submenu-toggle="hover">
                    <a href="javascript:;" class="kt-menu__link kt-menu__toggle">
                        <i class="kt-menu__link-icon flaticon2-cube"></i>
                        <span class="kt-menu__link-text">Equipments</span>
                        <i class="kt-menu__ver-arrow la la-angle-right"></i>
                    </a>
                    <div class="kt-menu__submenu ">
                        <span class="kt-menu__arrow"></span>
                        <ul class="kt-menu__subnav">
                            @if (UserContext.IsAdmin)
                            {
                                <li class="kt-menu__item " aria-haspopup="true">
                                    <a asp-controller="Equipment" asp-action="Add" class="kt-menu__link ">
                                        <i class="kt-menu__link-bullet kt-menu__link-bullet--dot"><span></span></i>
                                        <span class="kt-menu__link-text">Create equipment</span>
                                    </a>
                                </li>
                            }
                            <li class="kt-menu__item " aria-haspopup="true">
                                <a asp-controller="Equipment" asp-action="MyEquipments" class="kt-menu__link ">
                                    <i class="kt-menu__link-bullet kt-menu__link-bullet--dot"><span></span></i>
                                    <span class="kt-menu__link-text">My equipments</span>
                                </a>
                            </li>
                            @if (UserContext.IsAdmin)
                            {
                                <li class="kt-menu__item " aria-haspopup="true">
                                    <a asp-controller="Equipment" asp-action="Index" class="kt-menu__link ">
                                        <i class="kt-menu__link-bullet kt-menu__link-bullet--dot"><span></span></i>
                                        <span class="kt-menu__link-text">All equipments</span>
                                    </a>
                                </li>
                                <li class="kt-menu__item " aria-haspopup="true">
                                    <a asp-controller="Equipment" asp-action="UserEquipments" class="kt-menu__link ">
                                        <i class="kt-menu__link-bullet kt-menu__link-bullet--dot"><span></span></i>
                                        <span class="kt-menu__link-text">User equipments</span>
                                    </a>
                                </li>
                            }
                        </ul>
                    </div>
                </li>

                @if (UserContext.IsAdmin)
                {
                    <li class="kt-menu__section ">
                        <h4 class="kt-menu__section-text">Reports</h4>
                    </li>
                    <li class="kt-menu__item ">
                        <a asp-controller="Report" asp-action="Requests" class="kt-menu__link ">
                            <i class="kt-menu__link-icon flaticon2-zig-zag-line-sign"></i><span class="kt-menu__link-text">Requests</span>
                        </a>
                    </li>
                    <li class="kt-menu__item ">
                        <a asp-controller="Report" asp-action="Equipments" class="kt-menu__link ">
                            <i class="kt-menu__link-icon flaticon2-pie-chart-4"></i><span class="kt-menu__link-text">Equipments</span>
                        </a>
                    </li>
                }

            </ul>
        </div>
    </div>
</div>